package com.gobe.connector.application.util;

public enum VendorBookingStatus {

	CREATED,
	PROCESSING,
	CONFIRMED,
	CHECKED_VALID,
	ORDER_SPLIT_VALID,
	ON_VALIDATION,
	PAYMENT_AUTHORIZED,
	PRORATED_DISCOUNTS_CALCULATED,
	PAYMENT_AMOUNT_RESERVED,
	ORDER_BALANCE_SET,
	PAYMENT_CAPTURED,
	WAIT_FRAUD_MANUAL_CHECK,
	FRAUD_CHECKED,
	ORDER_SPLIT,
	PENDING_TOUR_OPERATOR_RESPONSE,
	COMPLETED,
	SUSPENDED,
	PROCESSING_ERROR,
	PAYMENT_NOT_AUTHORIZED,
	CHECKED_INVALID,
	ORDER_SPLIT_INVALID,
	PRORATED_DISCOUNTS_NOT_CALCULATED,
	PAYMENT_AMOUNT_NOT_RESERVED,
	PAYMENT_NOT_CAPTURED,
	PARTIAL_CANCELLED,
	CANCELLED,
	ERROR,
	CANCELLING;
	
}
