package com.placepass.utils.event;

public enum PlatformEventKey {
	
    PARTNER_ID,
    CUSTOMER_ID,
    ENTITY_ID,
    ENTITY_NAME,
    TRACE_ID,
    PLATFORM_EVENT_NAME,
    
    CUSTOMER_EMAIL,
    CUSTOMER_FIRST_NAME,
    BOOKER_FULL_NAME,
    LEAD_TRAVELLER_FULL_NAME,
    ORDER_ID,
    PRODUCT_TITLE,
    PRODUCT_DESCRIPTION,
    PRODUCT_IMAGE_URL,
    BOOKING_DATE,
    BOOKING_TIME,
    BOOKING_LOCATION,
    BOOKING_VOUCHER_URL,
    VENDOR,
    VENDOR_NAME,
    ORDER_TOTAL,
    BOOKING_ID,
    LAST_4_CARD_NUMBER,
    VENDOR_IMAGE_URL,
    CANCELLATION_POLICY,
    
    ADULT_VISIBILITY,
    CHILD_VISIBILITY,
    SENIOR_VISIBILITY,
    INFANT_VISIBILITY,
    YOUTH_VISIBILITY,
    
    BOOKING_TIME_VISIBILITY,
    
    SENIOR_COUNT,
    ADULT_COUNT,
    INFANT_COUNT,
    CHILD_COUNT,
    YOUTH_COUNT,
    
    SENIOR_PRICE,
    ADULT_PRICE,
    INFANT_PRICE,
    CHILD_PRICE,
    YOUTH_PRICE,
    
    SENIOR_TOTAL,
    ADULT_TOTAL,
    INFANT_TOTAL,
    CHILD_TOTAL,
    YOUTH_TOTAL,
    
    LOYALTY_PROG_NAME, LOYALTY_POINTS,
    
    LOYALTY_VISIBILITY,

    PICK_UP_LOCATION_NAME, PICK_UP_LOCATION_ADDRESS_ONE, PICK_UP_LOCATION_ADDRESS_CITY_STATE_ZIP, PICK_UP_LOCATION_DATE, PICK_UP_LOCATION_TIME, PICK_UP_LOCATION_PHONE, PICK_UP_LOCATION_FAX, PICK_UP_LOCATION_HOURS, DROP_OFF_LOCATION_NAME, DROP_OFF_LOCATION_ADDRESS_ONE, DROP_OFF_LOCATION_ADDRESS_CITY_STATE_ZIP, DROP_OFF_LOCATION_DATE, DROP_OFF_LOCATION_TIME, DROP_OFF_LOCATION_PHONE, DROP_OFF_LOCATION_FAX, DROP_OFF_LOCATION_HOURS,

    RENTAL_DURATION, RENTAL_RATE, RENTAL_RATE_DURATION,
    

    REFUND_AMOUNT,

    VERIFICATION_URL,
    
    RESET_PASSWORD_URL,
    
    ROLE,
    OLDROLE,
    PARTNER,
    FEE,
    FEE_VISIBILITY,
    DISCOUNT,
    DISCOUNT_VISIBILITY;
    
}
