package com.placepass.booking.domain.booking;
/**
 * Defines the Booking Event Names.
 *
 * @author arlene
 */
public enum EventName {
	
	PARTNER_CONFIG_RETRIEVED,
	CART_RETRIEVED,
	CART_VALIDATED,
	PRODUCT_DETAIL_RETRIEVAL_REQUEST_SENT,
	PRODUCT_DETAIL_RETRIEVAL_RESPONSE_RECEIVED,
	BOOKING_REFERENCE_GENERATED,
	LOYALTY_PROCESSED,
	DISCOUNT_PROCESSED,
	PAYMENT_REQUEST_SENT, 
	PAYMENT_RESPONSE_RECEIVED,
	BOOKING_REQUEST_SENT,
	BOOKING_RESPONSE_RECEIVED,
	CART_CLOSED,
	PAYMENT_REVERSAL_REQUEST_SENT,
	PAYMENT_REVERSAL_RESPONSE_RECEIVED,
	BOOKING_CANCEL_PROCESSING,
	BOOKING_CANCEL_REQUEST_SENT,
	BOOKING_CANCEL_RESPONSE_RECEIVED,
	PENDING_EMAIL_PROCESSED,
	CANCELLATION_EMAIL_PROCESSED,
	REJECTED_EMAIL_PROCESSED,
	CONFIRMATION_EMAIL_PROCESSED,
	BOOKING_STATUS_UPDATED,
	VOUCHER_RETRIEVAL_REQUEST_SENT,
	VOUCHER_RETRIEVAL_RESPONSE_RECEIVED,
	MANUAL_CANCEL_PROCESSING;
	
}
