//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.13 at 08:32:12 PM EDT 
//


package com.placepass.connector.citydiscovery.domain.citydiscovery.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActivityID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ActivityDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ActivityPrices">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ActivityPriceId">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ActivityPriceDays">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="Sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ActivityPriceOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityPriceOptionDepartureTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityPriceDateBegins" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="ActivityPriceDateEnds" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="ActivityPriceGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityPriceGroupMinPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityPriceGroupMaxPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityPriceAdult" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceAdultUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceAdultNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceAdultNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceAdultBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceAdultBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChild" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChildUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChildNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChildNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChildBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceChildBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityChildAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityChildMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityInfantAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityInfantMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityTotalPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityTotalPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityTotalPriceNet" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityTotalPriceNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceBeforeDiscount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ActivityPriceBeforeDiscountUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="ActivityPriceDiscountMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActivityPromoCodeMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ProcessType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activityID",
    "activityDate",
    "activityPrices"
})
@XmlRootElement(name = "CityDiscovery")
public class ClsPriceInfoRS {

    @XmlElement(name = "ActivityID")
    protected int activityID;
    @XmlElement(name = "ActivityDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activityDate;
    @XmlElement(name = "ActivityPrices", required = true)
    protected ClsPriceInfoRS.ActivityPrices activityPrices;
    @XmlAttribute(name = "ProcessType")
    protected String processType;

    /**
     * Gets the value of the activityID property.
     * 
     */
    public int getActivityID() {
        return activityID;
    }

    /**
     * Sets the value of the activityID property.
     * 
     */
    public void setActivityID(int value) {
        this.activityID = value;
    }

    /**
     * Gets the value of the activityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivityDate() {
        return activityDate;
    }

    /**
     * Sets the value of the activityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivityDate(XMLGregorianCalendar value) {
        this.activityDate = value;
    }

    /**
     * Gets the value of the activityPrices property.
     * 
     * @return
     *     possible object is
     *     {@link ClsPriceInfoRS.ActivityPrices }
     *     
     */
    public ClsPriceInfoRS.ActivityPrices getActivityPrices() {
        return activityPrices;
    }

    /**
     * Sets the value of the activityPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClsPriceInfoRS.ActivityPrices }
     *     
     */
    public void setActivityPrices(ClsPriceInfoRS.ActivityPrices value) {
        this.activityPrices = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessType(String value) {
        this.processType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ActivityPriceId">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ActivityPriceDays">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="Sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ActivityPriceOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityPriceOptionDepartureTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityPriceDateBegins" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="ActivityPriceDateEnds" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="ActivityPriceGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityPriceGroupMinPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityPriceGroupMaxPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityPriceAdult" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceAdultUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceAdultNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceAdultNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceAdultBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceAdultBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChild" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChildUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChildNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChildNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChildBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceChildBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityChildAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityChildMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityInfantAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityInfantMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityTotalPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityTotalPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityTotalPriceNet" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityTotalPriceNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceBeforeDiscount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ActivityPriceBeforeDiscountUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="ActivityPriceDiscountMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActivityPromoCodeMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activityPriceId"
    })
    public static class ActivityPrices {

        @XmlElement(name = "ActivityPriceId", required = true)
        protected List<ClsPriceInfoRS.ActivityPrices.ActivityPriceId> activityPriceId;

        /**
         * Gets the value of the activityPriceId property.
         * 
         * @return
         *     possible object is
         *     {@link PriceDetailByIdResponse.ActivityPrices.ActivityPriceId }
         *     
         *//*
        public PriceDetailByIdResponse.ActivityPrices.ActivityPriceId getActivityPriceId() {
            return activityPriceId;
        }

        *//**
         * Sets the value of the activityPriceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link ClsPriceInfoRS.ActivityPrices.ActivityPriceId }
         *     
         *//*
        public void setActivityPriceId(PriceDetailByIdResponse.ActivityPrices.ActivityPriceId value) {
            this.activityPriceId = value;
        }*/

        public List<ClsPriceInfoRS.ActivityPrices.ActivityPriceId> getActivityPriceId() {
            if (activityPriceId == null) {
             activityPriceId = new ArrayList<ClsPriceInfoRS.ActivityPrices.ActivityPriceId>();
            }
            return this.activityPriceId;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ActivityPriceDays">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="Sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ActivityPriceOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityPriceOptionDepartureTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityPriceDateBegins" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="ActivityPriceDateEnds" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="ActivityPriceGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityPriceGroupMinPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityPriceGroupMaxPax" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityPriceAdult" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceAdultUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceAdultNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceAdultNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceAdultBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceAdultBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChild" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChildUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChildNet" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChildNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChildBeforePromoCode" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceChildBeforePromoCodeUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityChildAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityChildMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityInfantAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityInfantMaxAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityTotalPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityTotalPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityTotalPriceNet" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityTotalPriceNetUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceBeforeDiscount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ActivityPriceBeforeDiscountUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="ActivityPriceDiscountMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActivityPromoCodeMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "activityPriceDays",
            "activityPriceOption",
            "activityPriceOptionDepartureTime",
            "activityPriceDateBegins",
            "activityPriceDateEnds",
            "activityPriceGroup",
            "activityPriceGroupMinPax",
            "activityPriceGroupMaxPax",
            "activityPriceAdult",
            "activityPriceAdultUSD",
            "activityPriceAdultNet",
            "activityPriceAdultNetUSD",
            "activityPriceAdultBeforePromoCode",
            "activityPriceAdultBeforePromoCodeUSD",
            "activityPriceChild",
            "activityPriceChildUSD",
            "activityPriceChildNet",
            "activityPriceChildNetUSD",
            "activityPriceChildBeforePromoCode",
            "activityPriceChildBeforePromoCodeUSD",
            "activityPriceCurrency",
            "activityChildAllowed",
            "activityChildMaxAge",
            "activityInfantAllowed",
            "activityInfantMaxAge",
            "activityTotalPrice",
            "activityTotalPriceUSD",
            "activityTotalPriceNet",
            "activityTotalPriceNetUSD",
            "activityPriceBeforeDiscount",
            "activityPriceBeforeDiscountUSD",
            "activityPriceDiscountMessage",
            "activityPromoCodeMessage"
        })
        public static class ActivityPriceId {

            @XmlElement(name = "ActivityPriceDays", required = true)
            protected ClsPriceInfoRS.ActivityPrices.ActivityPriceId.ActivityPriceDays activityPriceDays;
            @XmlElement(name = "ActivityPriceOption", required = true)
            protected String activityPriceOption;
            @XmlElement(name = "ActivityPriceOptionDepartureTime", required = true)
            protected String activityPriceOptionDepartureTime;
            @XmlElement(name = "ActivityPriceDateBegins", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar activityPriceDateBegins;
            @XmlElement(name = "ActivityPriceDateEnds", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar activityPriceDateEnds;
            @XmlElement(name = "ActivityPriceGroup", required = true)
            protected String activityPriceGroup;
            @XmlElement(name = "ActivityPriceGroupMinPax")
            protected int activityPriceGroupMinPax;
            @XmlElement(name = "ActivityPriceGroupMaxPax")
            protected int activityPriceGroupMaxPax;
            @XmlElement(name = "ActivityPriceAdult", required = true)
            protected BigDecimal activityPriceAdult;
            @XmlElement(name = "ActivityPriceAdultUSD", required = true)
            protected BigDecimal activityPriceAdultUSD;
            @XmlElement(name = "ActivityPriceAdultNet", required = true)
            protected BigDecimal activityPriceAdultNet;
            @XmlElement(name = "ActivityPriceAdultNetUSD", required = true)
            protected BigDecimal activityPriceAdultNetUSD;
            @XmlElement(name = "ActivityPriceAdultBeforePromoCode", required = true)
            protected BigDecimal activityPriceAdultBeforePromoCode;
            @XmlElement(name = "ActivityPriceAdultBeforePromoCodeUSD", required = true)
            protected BigDecimal activityPriceAdultBeforePromoCodeUSD;
            @XmlElement(name = "ActivityPriceChild", required = true)
            protected BigDecimal activityPriceChild;
            @XmlElement(name = "ActivityPriceChildUSD", required = true)
            protected BigDecimal activityPriceChildUSD;
            @XmlElement(name = "ActivityPriceChildNet", required = true)
            protected BigDecimal activityPriceChildNet;
            @XmlElement(name = "ActivityPriceChildNetUSD", required = true)
            protected BigDecimal activityPriceChildNetUSD;
            @XmlElement(name = "ActivityPriceChildBeforePromoCode", required = true)
            protected BigDecimal activityPriceChildBeforePromoCode;
            @XmlElement(name = "ActivityPriceChildBeforePromoCodeUSD", required = true)
            protected BigDecimal activityPriceChildBeforePromoCodeUSD;
            @XmlElement(name = "ActivityPriceCurrency", required = true)
            protected String activityPriceCurrency;
            @XmlElement(name = "ActivityChildAllowed", required = true)
            protected String activityChildAllowed;
            @XmlElement(name = "ActivityChildMaxAge")
            protected int activityChildMaxAge;
            @XmlElement(name = "ActivityInfantAllowed", required = true)
            protected String activityInfantAllowed;
            @XmlElement(name = "ActivityInfantMaxAge")
            protected int activityInfantMaxAge;
            @XmlElement(name = "ActivityTotalPrice")
            protected int activityTotalPrice;
            @XmlElement(name = "ActivityTotalPriceUSD", required = true)
            protected BigDecimal activityTotalPriceUSD;
            @XmlElement(name = "ActivityTotalPriceNet")
            protected int activityTotalPriceNet;
            @XmlElement(name = "ActivityTotalPriceNetUSD", required = true)
            protected BigDecimal activityTotalPriceNetUSD;
            @XmlElement(name = "ActivityPriceBeforeDiscount")
            protected int activityPriceBeforeDiscount;
            @XmlElement(name = "ActivityPriceBeforeDiscountUSD", required = true)
            protected BigDecimal activityPriceBeforeDiscountUSD;
            @XmlElement(name = "ActivityPriceDiscountMessage", required = true)
            protected String activityPriceDiscountMessage;
            @XmlElement(name = "ActivityPromoCodeMessage", required = true)
            protected String activityPromoCodeMessage;
            @XmlAttribute(name = "ID")
            protected Integer id;

            /**
             * Gets the value of the activityPriceDays property.
             * 
             * @return
             *     possible object is
             *     {@link ClsPriceInfoRS.ActivityPrices.ActivityPriceId.ActivityPriceDays }
             *     
             */
            public ClsPriceInfoRS.ActivityPrices.ActivityPriceId.ActivityPriceDays getActivityPriceDays() {
                return activityPriceDays;
            }

            /**
             * Sets the value of the activityPriceDays property.
             * 
             * @param value
             *     allowed object is
             *     {@link ClsPriceInfoRS.ActivityPrices.ActivityPriceId.ActivityPriceDays }
             *     
             */
            public void setActivityPriceDays(ClsPriceInfoRS.ActivityPrices.ActivityPriceId.ActivityPriceDays value) {
                this.activityPriceDays = value;
            }

            /**
             * Gets the value of the activityPriceOption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPriceOption() {
                return activityPriceOption;
            }

            /**
             * Sets the value of the activityPriceOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPriceOption(String value) {
                this.activityPriceOption = value;
            }

            /**
             * Gets the value of the activityPriceOptionDepartureTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPriceOptionDepartureTime() {
                return activityPriceOptionDepartureTime;
            }

            /**
             * Sets the value of the activityPriceOptionDepartureTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPriceOptionDepartureTime(String value) {
                this.activityPriceOptionDepartureTime = value;
            }

            /**
             * Gets the value of the activityPriceDateBegins property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getActivityPriceDateBegins() {
                return activityPriceDateBegins;
            }

            /**
             * Sets the value of the activityPriceDateBegins property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setActivityPriceDateBegins(XMLGregorianCalendar value) {
                this.activityPriceDateBegins = value;
            }

            /**
             * Gets the value of the activityPriceDateEnds property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getActivityPriceDateEnds() {
                return activityPriceDateEnds;
            }

            /**
             * Sets the value of the activityPriceDateEnds property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setActivityPriceDateEnds(XMLGregorianCalendar value) {
                this.activityPriceDateEnds = value;
            }

            /**
             * Gets the value of the activityPriceGroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPriceGroup() {
                return activityPriceGroup;
            }

            /**
             * Sets the value of the activityPriceGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPriceGroup(String value) {
                this.activityPriceGroup = value;
            }

            /**
             * Gets the value of the activityPriceGroupMinPax property.
             * 
             */
            public int getActivityPriceGroupMinPax() {
                return activityPriceGroupMinPax;
            }

            /**
             * Sets the value of the activityPriceGroupMinPax property.
             * 
             */
            public void setActivityPriceGroupMinPax(int value) {
                this.activityPriceGroupMinPax = value;
            }

            /**
             * Gets the value of the activityPriceGroupMaxPax property.
             * 
             */
            public int getActivityPriceGroupMaxPax() {
                return activityPriceGroupMaxPax;
            }

            /**
             * Sets the value of the activityPriceGroupMaxPax property.
             * 
             */
            public void setActivityPriceGroupMaxPax(int value) {
                this.activityPriceGroupMaxPax = value;
            }

            /**
             * Gets the value of the activityPriceAdult property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdult() {
                return activityPriceAdult;
            }

            /**
             * Sets the value of the activityPriceAdult property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdult(BigDecimal value) {
                this.activityPriceAdult = value;
            }

            /**
             * Gets the value of the activityPriceAdultUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdultUSD() {
                return activityPriceAdultUSD;
            }

            /**
             * Sets the value of the activityPriceAdultUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdultUSD(BigDecimal value) {
                this.activityPriceAdultUSD = value;
            }

            /**
             * Gets the value of the activityPriceAdultNet property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdultNet() {
                return activityPriceAdultNet;
            }

            /**
             * Sets the value of the activityPriceAdultNet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdultNet(BigDecimal value) {
                this.activityPriceAdultNet = value;
            }

            /**
             * Gets the value of the activityPriceAdultNetUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdultNetUSD() {
                return activityPriceAdultNetUSD;
            }

            /**
             * Sets the value of the activityPriceAdultNetUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdultNetUSD(BigDecimal value) {
                this.activityPriceAdultNetUSD = value;
            }

            /**
             * Gets the value of the activityPriceAdultBeforePromoCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdultBeforePromoCode() {
                return activityPriceAdultBeforePromoCode;
            }

            /**
             * Sets the value of the activityPriceAdultBeforePromoCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdultBeforePromoCode(BigDecimal value) {
                this.activityPriceAdultBeforePromoCode = value;
            }

            /**
             * Gets the value of the activityPriceAdultBeforePromoCodeUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceAdultBeforePromoCodeUSD() {
                return activityPriceAdultBeforePromoCodeUSD;
            }

            /**
             * Sets the value of the activityPriceAdultBeforePromoCodeUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceAdultBeforePromoCodeUSD(BigDecimal value) {
                this.activityPriceAdultBeforePromoCodeUSD = value;
            }

            /**
             * Gets the value of the activityPriceChild property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChild() {
                return activityPriceChild;
            }

            /**
             * Sets the value of the activityPriceChild property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChild(BigDecimal value) {
                this.activityPriceChild = value;
            }

            /**
             * Gets the value of the activityPriceChildUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChildUSD() {
                return activityPriceChildUSD;
            }

            /**
             * Sets the value of the activityPriceChildUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChildUSD(BigDecimal value) {
                this.activityPriceChildUSD = value;
            }

            /**
             * Gets the value of the activityPriceChildNet property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChildNet() {
                return activityPriceChildNet;
            }

            /**
             * Sets the value of the activityPriceChildNet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChildNet(BigDecimal value) {
                this.activityPriceChildNet = value;
            }

            /**
             * Gets the value of the activityPriceChildNetUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChildNetUSD() {
                return activityPriceChildNetUSD;
            }

            /**
             * Sets the value of the activityPriceChildNetUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChildNetUSD(BigDecimal value) {
                this.activityPriceChildNetUSD = value;
            }

            /**
             * Gets the value of the activityPriceChildBeforePromoCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChildBeforePromoCode() {
                return activityPriceChildBeforePromoCode;
            }

            /**
             * Sets the value of the activityPriceChildBeforePromoCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChildBeforePromoCode(BigDecimal value) {
                this.activityPriceChildBeforePromoCode = value;
            }

            /**
             * Gets the value of the activityPriceChildBeforePromoCodeUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceChildBeforePromoCodeUSD() {
                return activityPriceChildBeforePromoCodeUSD;
            }

            /**
             * Sets the value of the activityPriceChildBeforePromoCodeUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceChildBeforePromoCodeUSD(BigDecimal value) {
                this.activityPriceChildBeforePromoCodeUSD = value;
            }

            /**
             * Gets the value of the activityPriceCurrency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPriceCurrency() {
                return activityPriceCurrency;
            }

            /**
             * Sets the value of the activityPriceCurrency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPriceCurrency(String value) {
                this.activityPriceCurrency = value;
            }

            /**
             * Gets the value of the activityChildAllowed property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityChildAllowed() {
                return activityChildAllowed;
            }

            /**
             * Sets the value of the activityChildAllowed property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityChildAllowed(String value) {
                this.activityChildAllowed = value;
            }

            /**
             * Gets the value of the activityChildMaxAge property.
             * 
             */
            public int getActivityChildMaxAge() {
                return activityChildMaxAge;
            }

            /**
             * Sets the value of the activityChildMaxAge property.
             * 
             */
            public void setActivityChildMaxAge(int value) {
                this.activityChildMaxAge = value;
            }

            /**
             * Gets the value of the activityInfantAllowed property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityInfantAllowed() {
                return activityInfantAllowed;
            }

            /**
             * Sets the value of the activityInfantAllowed property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityInfantAllowed(String value) {
                this.activityInfantAllowed = value;
            }

            /**
             * Gets the value of the activityInfantMaxAge property.
             * 
             */
            public int getActivityInfantMaxAge() {
                return activityInfantMaxAge;
            }

            /**
             * Sets the value of the activityInfantMaxAge property.
             * 
             */
            public void setActivityInfantMaxAge(int value) {
                this.activityInfantMaxAge = value;
            }

            /**
             * Gets the value of the activityTotalPrice property.
             * 
             */
            public int getActivityTotalPrice() {
                return activityTotalPrice;
            }

            /**
             * Sets the value of the activityTotalPrice property.
             * 
             */
            public void setActivityTotalPrice(int value) {
                this.activityTotalPrice = value;
            }

            /**
             * Gets the value of the activityTotalPriceUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityTotalPriceUSD() {
                return activityTotalPriceUSD;
            }

            /**
             * Sets the value of the activityTotalPriceUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityTotalPriceUSD(BigDecimal value) {
                this.activityTotalPriceUSD = value;
            }

            /**
             * Gets the value of the activityTotalPriceNet property.
             * 
             */
            public int getActivityTotalPriceNet() {
                return activityTotalPriceNet;
            }

            /**
             * Sets the value of the activityTotalPriceNet property.
             * 
             */
            public void setActivityTotalPriceNet(int value) {
                this.activityTotalPriceNet = value;
            }

            /**
             * Gets the value of the activityTotalPriceNetUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityTotalPriceNetUSD() {
                return activityTotalPriceNetUSD;
            }

            /**
             * Sets the value of the activityTotalPriceNetUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityTotalPriceNetUSD(BigDecimal value) {
                this.activityTotalPriceNetUSD = value;
            }

            /**
             * Gets the value of the activityPriceBeforeDiscount property.
             * 
             */
            public int getActivityPriceBeforeDiscount() {
                return activityPriceBeforeDiscount;
            }

            /**
             * Sets the value of the activityPriceBeforeDiscount property.
             * 
             */
            public void setActivityPriceBeforeDiscount(int value) {
                this.activityPriceBeforeDiscount = value;
            }

            /**
             * Gets the value of the activityPriceBeforeDiscountUSD property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivityPriceBeforeDiscountUSD() {
                return activityPriceBeforeDiscountUSD;
            }

            /**
             * Sets the value of the activityPriceBeforeDiscountUSD property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivityPriceBeforeDiscountUSD(BigDecimal value) {
                this.activityPriceBeforeDiscountUSD = value;
            }

            /**
             * Gets the value of the activityPriceDiscountMessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPriceDiscountMessage() {
                return activityPriceDiscountMessage;
            }

            /**
             * Sets the value of the activityPriceDiscountMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPriceDiscountMessage(String value) {
                this.activityPriceDiscountMessage = value;
            }

            /**
             * Gets the value of the activityPromoCodeMessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActivityPromoCodeMessage() {
                return activityPromoCodeMessage;
            }

            /**
             * Sets the value of the activityPromoCodeMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActivityPromoCodeMessage(String value) {
                this.activityPromoCodeMessage = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setID(Integer value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="Sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday"
            })
            public static class ActivityPriceDays {

                @XmlElement(name = "Monday")
                protected boolean monday;
                @XmlElement(name = "Tuesday")
                protected boolean tuesday;
                @XmlElement(name = "Wednesday")
                protected boolean wednesday;
                @XmlElement(name = "Thursday")
                protected boolean thursday;
                @XmlElement(name = "Friday")
                protected boolean friday;
                @XmlElement(name = "Saturday")
                protected boolean saturday;
                @XmlElement(name = "Sunday")
                protected boolean sunday;

                /**
                 * Gets the value of the monday property.
                 * 
                 */
                public boolean isMonday() {
                    return monday;
                }

                /**
                 * Sets the value of the monday property.
                 * 
                 */
                public void setMonday(boolean value) {
                    this.monday = value;
                }

                /**
                 * Gets the value of the tuesday property.
                 * 
                 */
                public boolean isTuesday() {
                    return tuesday;
                }

                /**
                 * Sets the value of the tuesday property.
                 * 
                 */
                public void setTuesday(boolean value) {
                    this.tuesday = value;
                }

                /**
                 * Gets the value of the wednesday property.
                 * 
                 */
                public boolean isWednesday() {
                    return wednesday;
                }

                /**
                 * Sets the value of the wednesday property.
                 * 
                 */
                public void setWednesday(boolean value) {
                    this.wednesday = value;
                }

                /**
                 * Gets the value of the thursday property.
                 * 
                 */
                public boolean isThursday() {
                    return thursday;
                }

                /**
                 * Sets the value of the thursday property.
                 * 
                 */
                public void setThursday(boolean value) {
                    this.thursday = value;
                }

                /**
                 * Gets the value of the friday property.
                 * 
                 */
                public boolean isFriday() {
                    return friday;
                }

                /**
                 * Sets the value of the friday property.
                 * 
                 */
                public void setFriday(boolean value) {
                    this.friday = value;
                }

                /**
                 * Gets the value of the saturday property.
                 * 
                 */
                public boolean isSaturday() {
                    return saturday;
                }

                /**
                 * Sets the value of the saturday property.
                 * 
                 */
                public void setSaturday(boolean value) {
                    this.saturday = value;
                }

                /**
                 * Gets the value of the sunday property.
                 * 
                 */
                public boolean isSunday() {
                    return sunday;
                }

                /**
                 * Sets the value of the sunday property.
                 * 
                 */
                public void setSunday(boolean value) {
                    this.sunday = value;
                }

            }

        }

    }

}
